version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    environment:
      - POSTGRESQL__DSN=postgres://${POSTGRES_NS_USERNAME}:${POSTGRES_NS_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NS_DATABASE}?sslmode=${POSTGRES_SSLMODE}
      - REDIS__URL=redis://redis:6379
      - NETWORK_SERVER__BAND__NAME=EU868
      - NETWORK_SERVER__GATEWAY__BACKEND__MQTT__SERVER=tcp://mosquitto:1883
      - JOIN_SERVER__DEFAULT__SERVER=http://chirpstack-application-server:8003
    depends_on:
      - mosquitto

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    ports:
      - 80:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    environment:
      - POSTGRESQL__DSN=postgres://${POSTGRES_AS_USERNAME}:${POSTGRES_AS_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_AS_DATABASE}?sslmode=${POSTGRES_SSLMODE}
      - REDIS__URL=redis://redis:6379
      - APPLICATION_SERVER__INTEGRATION__MQTT__SERVER=tcp://mosquitto:1883
      - APPLICATION_SERVER__INTEGRATION__POSTGRES__DSN=postgres://${POSTGRES_LORASTORE_USERNAME}:${POSTGRES_LORASTORE_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_LORASTORE_DATABASE}?sslmode=${POSTGRES_SSLMODE}
      - APPLICATION_SERVER__API__PUBLIC_HOST=chirpstack-application-server:8001
      - APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET=${APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET}
    depends_on:
      - chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION__MQTT__AUTH__GENERIC__SERVERS=tcp://mosquitto:1883
    depends_on: 
      - mosquitto

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - 1883:1883

volumes:
  redisdata:
