# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://$POSTGRES_AS_USERNAME:$POSTGRES_AS_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_AS_DATABASE?sslmode=$POSTGRES_SSLMODE"

[redis]
url="redis://redis:6379"

[application_server.integration]
# Enabled integrations.
enabled=["mqtt","postgresql"]

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"

[application_server.integration.postgresql]
dsn="postgres://$POSTGRES_LORASTORE_USERNAME:$POSTGRES_LORASTORE_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_LORASTORE_DATABASE?sslmode=$POSTGRES_SSLMODE"

[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="$APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET"
