# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://chirpstack_as:QCDPdUJqkAp6oAuXtfwsT2HRPhfbiE@db-kronjuvelen-do-user-8826297-0.b.db.ondigitalocean.com:25060/chirpstack_as?sslmode=require"

[redis]
url="redis://redis:6379"

[application_server.integration]
marshaler="json"
# Enabled integrations.
enabled=["mqtt","postgresql"]

[application_server.integration.mqtt]
server="tcp://mosquitto:1883"

[application_server.integration.postgresql]
dsn="postgres://chirpstack_lorastore:bCbYkintUTQaUJ26a4YQwmVLZvZEiB@db-kronjuvelen-do-user-8826297-0.b.db.ondigitalocean.com:25060/chirpstack_lorastore?sslmode=require"

[application_server.api]
public_host="chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="$APPLICATION_SERVER__EXTERNAL_API__JWT_SECRET"
